# this dockerfile allow to develop application code without installing NodeJS/VueJS on local computer (note: node_modules will not be on local).

# build image: `docker build -f docker/Dockerfile-dev -t nioc/vue-dom:node-alpine-dev .`
# start image: `docker run -it -p 3000:3000 --rm -v "$(pwd)":/app -v "/app/node_modules" --name vue-dom-1 nioc/vue-dom:node-alpine-dev`

FROM node:lts-alpine

# install app dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install && chown node:node -R /app

# start vite dev server
EXPOSE 3000
USER node
CMD ["npm", "run", "dev"]
