# this dockerfile serve static files from builded VueJS app with nginx.

# Production stage (build was made previously)
FROM nginx:stable-alpine as production-stage

# copy html files
COPY vue-dom /usr/share/nginx/html

# copy nginx custom entrypoint
COPY ./docker/998-update-local.js.sh /docker-entrypoint.d/998-update-local.js.sh

# set environment variables
ENV TITLE=
ENV PROVIDER=
ENV COMPONENTS=
ENV EVENTS_READ_DELAY=

# tag image with commit SHA and date
ARG GIT_COMMIT=unspecified
ARG BUILD_DATE
ARG VERSION=unspecified
LABEL org.label-schema.name="vue-dom"
LABEL org.label-schema.vendor="nioc"
LABEL org.label-schema.license="AGPL-3.0-or-later"
LABEL org.label-schema.vcs-url="https://github.com/nioc/vue-dom"
LABEL org.label-schema.vcs-ref=$GIT_COMMIT
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.version=$VERSION
LABEL maintainer="nioc <dev@nioc.eu>"
